## **Adult Census Income**

This notebook will outline a tutorial on how to create subsets for this data utilizing python

## Tutorial outline



1.   Setup
2.   Observing data
3. Creating subsets
4. Merging subsets

## **1. Setup**



*   First, you will need to download the adult.csv file using this [webpage](https://www.kaggle.com/datasets/lovishbansal123/adult-census-income)
*   Once that is downloaded, upload it into your google drive (Within drive locate the +new button and click file upload)
*   Direct back to python and mount your google drive in order to pull csv file from

*Remember, to activate code, click on the button to the left of the code. A green check mark should pop up once complete*

In [6]:
from google.colab import drive
drive.mount ('/content/gdrive')

Mounted at /content/gdrive



*   Next, we import pandas an numpy into our notebook in order to manipulate the data
*   To simplify coding later on, we define pandas as pd and numpy as np

*Use the code below*

In [ ]:
import pandas as pd
import numpy as np



*   Import/read the csv file from your google drive by using the following code
*   We will also define define the file as "df" within the code

In [7]:
df= pd.read_csv('gdrive/My Drive/Colab Notebooks/adult.csv')

In [12]:
df

,age,workclass,fnlwgt,education,education.num,marital.status,occupation,relationship,race,sex,capital.gain,capital.loss,hours.per.week,native.country,income
0,90,?,77053,HS-grad,9,Widowed,?,Not-in-family,White,Female,0,4356,40,United-States,<=50K
1,82,Private,132870,HS-grad,9,Widowed,Exec-managerial,Not-in-family,White,Female,0,4356,18,United-States,<=50K
2,66,?,186061,Some-college,10,Widowed,?,Unmarried,Black,Female,0,4356,40,United-States,<=50K
3,54,Private,140359,7th-8th,4,Divorced,Machine-op-inspct,Unmarried,White,Female,0,3900,40,United-States,<=50K
4,41,Private,264663,Some-college,10,Separated,Prof-specialty,Own-child,White,Female,0,3900,40,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,22,Private,310152,Some-college,10,Never-married,Protective-serv,Not-in-family,White,Male,0,0,40,United-States,<=50K
32557,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
32558,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
32559,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
32560,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K

## **2. Observing and Filtering our Data**

Now, we can explore different qualities of our dataset.


*   To find the shape, or number of columns/rows, use the following code

In [13]:
df.shape

(32561, 15)



*   To find the total number of cells use the size code below

In [14]:
df.size

488415



*   Lastly, to find the names of all the columns, use the following

In [15]:
df.columns

Index(['age', 'workclass', 'fnlwgt', 'education', 'education.num',
       'marital.status', 'occupation', 'relationship', 'race', 'sex',
       'capital.gain', 'capital.loss', 'hours.per.week', 'native.country',
       'income'],
      dtype='object')

Now, we can narrow down the columns by using df.loc[] and including only the ones we want.

In this case we only use the columns: age, education, marital.status, race, sex, and income.

*Use the code below*

In [16]:
df.loc[:,["age", "education", "marital.status", "race", "sex", "income"]]

       age     education      marital.status   race     sex income
0       90       HS-grad             Widowed  White  Female  <=50K
1       82       HS-grad             Widowed  White  Female  <=50K
2       66  Some-college             Widowed  Black  Female  <=50K
3       54       7th-8th            Divorced  White  Female  <=50K
4       41  Some-college           Separated  White  Female  <=50K
...    ...           ...                 ...    ...     ...    ...
32556   22  Some-college       Never-married  White    Male  <=50K
32557   27    Assoc-acdm  Married-civ-spouse  White  Female  <=50K
32558   40       HS-grad  Married-civ-spouse  White    Male   >50K
32559   58       HS-grad             Widowed  White  Female  <=50K
32560   22       HS-grad       Never-married  White    Male  <=50K

[32561 rows x 6 columns]

# **3. Creating Subsets**

* Next, we can create our first subset
from the data

* Since we are analyzing trends of education levels correlating to income, sort the data by High School graduates versus those with a Bachelors degree.




*   Use the code below to first complile only the data for High School graduates.

In [24]:
df["education"] == "HS-grad"

0         True
1         True
2        False
3        False
4        False
         ...
32556    False
32557    False
32558     True
32559     True
32560     True
Name: education, Length: 32561, dtype: bool



Once your green check mark appears, we need to create our first subset of this filtered data
*   The first subset will be defined as "first_subset"
*   The code below creates the subset using df.loc[:,] with the relevant column names inside, along with the narrowed down code for HS-grad education level (the code above)

*Apply the following code*

In [25]:
first_subset = df.loc [:, ["age", "education", "marital.status", "race", "sex", "income"]][df["education"]== "HS-grad"]

In [26]:
first_subset

       age education      marital.status   race     sex income
0       90   HS-grad             Widowed  White  Female  <=50K
1       82   HS-grad             Widowed  White  Female  <=50K
5       34   HS-grad            Divorced  White  Female  <=50K
8       68   HS-grad            Divorced  White  Female  <=50K
22      61   HS-grad            Divorced  White  Female  <=50K
...    ...       ...                 ...    ...     ...    ...
32544   72   HS-grad  Married-civ-spouse  White    Male  <=50K
32549   43   HS-grad  Married-civ-spouse  White    Male  <=50K
32558   40   HS-grad  Married-civ-spouse  White    Male   >50K
32559   58   HS-grad             Widowed  White  Female  <=50K
32560   22   HS-grad       Never-married  White    Male  <=50K

[10501 rows x 6 columns]



*   Follow the same step for creating the second subset, but replace "HS-grad" with "Bachelors"
*   This one will be defined as second_subset

In [31]:
second_subset = df.loc[:, ["age", "education", "marital.status", "race", "sex", "income"]][df["education"]== "Bachelors"]

In [32]:
second_subset

       age  education      marital.status                race     sex income
12      52  Bachelors             Widowed               White  Female   >50K
19      34  Bachelors           Separated               White    Male   >50K
20      37  Bachelors       Never-married               White    Male   >50K
33      51  Bachelors            Divorced               White    Male   >50K
40      44  Bachelors            Divorced               White    Male   >50K
...    ...        ...                 ...                 ...     ...    ...
32516   25  Bachelors       Never-married               Black  Female  <=50K
32533   35  Bachelors  Married-civ-spouse               White  Female   >50K
32534   30  Bachelors       Never-married  Asian-Pac-Islander  Female  <=50K
32536   54  Bachelors  Married-civ-spouse  Asian-Pac-Islander    Male   >50K
32539   34  Bachelors       Never-married               White  Female   >50K

[5355 rows x 6 columns]

# **4. Merging Subsets**

To analyze trends between High School graduates compared to 4-year College graduates, we need to merge our two data sets.


*   Use the pd.concat() function to do so, typing the first and second dataset names within the parentheses.

* We also label the merged data within the code

*Use the following code*

In [33]:
merged_data = pd.concat ([first_subset, second_subset]).copy()

In [41]:
merged_data

       age  education      marital.status                race     sex income
0       90    HS-grad             Widowed               White  Female  <=50K
1       82    HS-grad             Widowed               White  Female  <=50K
5       34    HS-grad            Divorced               White  Female  <=50K
8       68    HS-grad            Divorced               White  Female  <=50K
22      61    HS-grad            Divorced               White  Female  <=50K
...    ...        ...                 ...                 ...     ...    ...
32516   25  Bachelors       Never-married               Black  Female  <=50K
32533   35  Bachelors  Married-civ-spouse               White  Female   >50K
32534   30  Bachelors       Never-married  Asian-Pac-Islander  Female  <=50K
32536   54  Bachelors  Married-civ-spouse  Asian-Pac-Islander    Male   >50K
32539   34  Bachelors       Never-married               White  Female   >50K

[15856 rows x 6 columns]



*   **Lastly,** export newly created merged dataset as a csv file
*   Use the .to_csv fundtion and add "index=False" at the end to avoid a row of indicies that pandas automatically creates

In [39]:
merged_data.to_csv("EducationLevelDifferences.csv", index=False)



*   Use the code below to download the csv

In [40]:
from google.colab import files
files.download('EducationLevelDifferences.csv')